[tool.poetry]
name = "hb"
version = "1.1.0"
description = "A simple command-line file hashing utility."
authors = ["Ching Chow <ching.chow.sc@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^6.7"

[tool.poetry.dev-dependencies]
codecov = "^2.0"
mypy = "^0.620.0"
pylint = "^2.0"
pytest = "^3.0"
rope = "^0.10.7"
