version: 2

jobs:
  python-latest:
    docker:
      - image: circleci/python:3.6.5

    steps:
      - checkout

      - restore_cache:
          key: pip-cache-2018.1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Install Dependencies
          command: pipenv install -d
          environment:
            PIPENV_VENV_IN_PROJECT: 1

      - save_cache:
          key: pip-cache-2018.1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - .venv

      - run:
          name: Run Tests
          command: pipenv run coverage run -m pytest --junit-xml=test-results/pytest/results.xml

      - run:
          name: Submit Code Coverage
          command: pipenv run codecov
          when: always

      - run:
          name: Mypy
          command: pipenv run mypy --strict hb
          when: always

      - run:
          name: Pylint
          # C0111: missing-docstring
          # C0301: line-too-long
          command: |
            pipenv run pylint -d C0301 hb
            pipenv run pylint -d C0111,C0301 tests
          when: always

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          destination: test-results

workflows:
  version: 2

  build:
    jobs:
      - python-latest
