aliases:

  - &py37 3.7.3
  - &py36 3.6.8

  - &args
    parameters:
      version:
        type: string
        default: latest

  - &docker_env
    docker:
      - image: circleci/python:<< parameters.version >>
        environment:
          TZ: America/New_York

  - &restore_cache
    restore_cache:
      keys:
        - &pk v1-python-<< parameters.version >>-cache-{{ .Branch }}-{{ checksum "poetry.lock" }}
        - v1-python-<< parameters.version >>-cache-{{ .Branch }}
        - v1-python-<< parameters.version >>-cache

  - &save_cache
    save_cache:
      key: *pk
      paths:
        - .venv

version: 2.1

commands:

  artifacts:
    steps:
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results

  install:
    steps:
      - run:
          name: Install dependencies
          command: |
            poetry config settings.virtualenvs.in-project true
            poetry install
            echo 'source .venv/bin/activate' >> "${BASH_ENV}"

  lint:
    steps:
      - run:
          name: Pylint
          command: |
            pylint hb
          when: always
      - run:
          name: Mypy
          command: |
            mypy hb
          when: always

  test:
    steps:
      - run:
          name: Pytest
          command: |
            pytest
      - run:
          name: Coverage
          command: |
            coverage report
            coverage html --directory=test-results/coverage
            codecov

jobs:

  test:
    <<: *args
    <<: *docker_env
    steps:
      - checkout
      - *restore_cache
      - install
      - test
      - lint
      - artifacts

  cache:
    <<: *args
    <<: *docker_env
    steps:
      - checkout
      - *restore_cache
      - install
      - *save_cache

workflows:

  version: 2

  commit: &test
    jobs:
      - test:
          name: Python 3.7
          version: *py37
      - test:
          name: Python 3.6
          version: *py36

  weekly:
    <<: *test
    triggers:
      - schedule:
          cron: 0 23 * * 0
          filters:
            branches:
              only:
                - master

  cache:
    jobs:
      - cache:
          name: Cache 3.7
          version: *py37
      - cache:
          name: Cache 3.6
          version: *py36
    triggers:
      - schedule:
          cron: 0 22 * * 0
          filters:
            branches:
              only:
                - master
