version: 2

jobs:
  cache:
    docker: &python_latest
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache: &restore_cache
          key: pip-cache-2018.1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install dependencies
          command: pipenv sync -d
          environment:
            PIPENV_VENV_IN_PROJECT: 1
      - save_cache:
          key: pip-cache-2018.1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - .venv

  test:
    docker: *python_latest
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run:
          name: Test
          command: pipenv run coverage run -m pytest --junit-xml=test-results/pytest/results.xml
      - run:
          name: Codecov
          command: pipenv run codecov
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results

  lint:
    docker: *python_latest
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run:
          name: Mypy
          command: |
            pipenv run mypy --ignore-missing-imports --strict hb
            pipenv run mypy --ignore-missing-imports --strict tests
          when: always
      - run:
          name: Pylint
          # C0111: missing-docstring
          # C0301: line-too-long
          # C0411: wrong-import-order
          # E1120: no-value-for-parameter
          # E1135: unsupported-membership-test
          # E1136: unsubscriptable-object
          # E1137: unsupported-assignment-operation
          command: |
            pipenv run pylint -d C0301,C0411,E1120,E1135,E1136,E1137 hb
            pipenv run pylint -d C0111,C0301 tests
          when: always

workflows:
  version: 2

  commit:
    jobs:
      - cache
      - test:
          requires:
            - cache
      - lint:
          requires:
            - cache

  weekly:
    jobs:
      - test
    triggers:
      - schedule:
          cron: "1 0 * * 1"
          filters:
            branches:
              only:
                - master
