name: Test

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: test-${{ github.actor }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"

      - run: poetry install

      - run: poetry run black .

      - run: poetry run isort .

      - run: poetry run flake8 .

      - run: poetry run mypy .

      - run: poetry run bandit --recursive hb

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.11"]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - run: poetry install

      - run: poetry run pytest
